import math

SPEED_OF_SOUND = 343.
D = 0.0457
PI = math.pi

SAMPLE_RATE = 16000
CHUNK = 256
NUM_OF_SNAPSHOTS_FOR_MUSIC = 16
REACTION_TIME = 4
NUM_OF_MICS = 4
RECORD_SECONDS = 32
RECORD_BUFFER_MAX = (SAMPLE_RATE * RECORD_SECONDS) // CHUNK

THRESHOLD_FOR_MODE = 10
